"""
Displacement and velocity processing from image correlation results.

This module handles loading, filtering, and time-series analysis of
displacement maps generated by image correlation tools (COSI-Corr, etc.).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

import dask.array as da
import numpy as np
import xarray as xr
from numpy.typing import NDArray
from scipy import ndimage

if TYPE_CHECKING:
    from ..config import TSCorrConfig


@dataclass
class DisplacementPair:
    """Container for a single displacement measurement pair."""
    filepath: Path
    date_master: datetime
    date_secondary: datetime
    dx: xr.DataArray | None = None
    dy: xr.DataArray | None = None
    
    @property
    def time_delta_days(self) -> float:
        """Time difference in days between image pair."""
        return (self.date_secondary - self.date_master).days

    @property
    def time_delta_years(self) -> float:
        """Time difference in years between image pair."""
        return self.time_delta_days / 365.25


def parse_correlation_filename(filename: str) -> tuple[datetime, datetime]:
    """
    Parse master and secondary dates from correlation result filename.

    Expected formats:
    - correlation_YYYYMMDDHHMMSS_*_vs_YYYYMMDDHHMMSS_*
    - YYYYMMDDHHMMSS_*_vs_YYYYMMDDHHMMSS_*
    - Various sensor-specific patterns

    Parameters
    ----------
    filename : str
        Filename to parse.

    Returns
    -------
    tuple
        (master_date, secondary_date) as datetime objects.
    """
    name = Path(filename).stem

    # Try standard pattern: correlation_YYYYMMDDHHMMSS_*_vs_YYYYMMDDHHMMSS_*
    pattern = r"correlation_(\d{14}).*?_vs_(\d{14})"
    match = re.search(pattern, name)
    if match:
        date_master = datetime.strptime(match.group(1), "%Y%m%d%H%M%S")
        date_secondary = datetime.strptime(match.group(2), "%Y%m%d%H%M%S")
        return date_master, date_secondary

    # Try shorter date format: YYYYMMDD
    pattern = r"(\d{8}).*?_vs_(\d{8})"
    match = re.search(pattern, name)
    if match:
        date_master = datetime.strptime(match.group(1), "%Y%m%d")
        date_secondary = datetime.strptime(match.group(2), "%Y%m%d")
        return date_master, date_secondary

    # Try extracting any 8 or 14 digit sequences
    dates = re.findall(r"\d{8,14}", name)
    if len(dates) >= 2:
        fmt = "%Y%m%d%H%M%S" if len(dates[0]) == 14 else "%Y%m%d"
        date_master = datetime.strptime(dates[0][:14 if len(dates[0]) >= 14 else 8], fmt)
        date_secondary = datetime.strptime(dates[1][:14 if len(dates[1]) >= 14 else 8], fmt)
        return date_master, date_secondary

    raise ValueError(f"Could not parse dates from filename: {filename}")


def load_displacement_pair(
    filepath: str | Path,
    config: TSCorrConfig,
    chunks: dict[str, int] | None = None,
) -> DisplacementPair:
    """
    Load a displacement pair from correlation result file.

    Parameters
    ----------
    filepath : str or Path
        Path to the displacement file.
    config : TSCorrConfig
        Configuration object.
    chunks : dict, optional
        Chunk sizes for dask arrays.

    Returns
    -------
    DisplacementPair
        Loaded displacement data.
    """
    from ..io.raster import read_geotiff, read_envi

    filepath = Path(filepath)
    date_master, date_secondary = parse_correlation_filename(filepath.name)

    pair = DisplacementPair(
        filepath=filepath,
        date_master=date_master,
        date_secondary=date_secondary,
    )

    # Determine reader based on tool and file format
    tool = config.processing.tool

    if tool == config.processing.COSI_CORR:
        # ENVI format with .hdr
        data = read_envi(filepath, chunks=chunks)
        pair.dx = data.isel(band=0) if "band" in data.dims else data[:, :, 0]
        pair.dy = data.isel(band=1) if "band" in data.dims else data[:, :, 1]

    elif tool == config.processing.SETSM_SDM:
        # Separate dx/dy GeoTIFF files
        dx_file = filepath
        dy_file = Path(str(filepath).replace("dx.tif", "dy.tif"))
        
        pair.dx = read_geotiff(dx_file, chunks=chunks)
        pair.dy = read_geotiff(dy_file, chunks=chunks)
        
        # Convert from rate (m/day) to displacement (m)
        dt = pair.time_delta_days
        pair.dx = pair.dx * dt
        pair.dy = pair.dy * dt

    elif tool == config.processing.COSI_CORR_PLUS:
        # Multi-band GeoTIFF
        data = read_geotiff(filepath, chunks=chunks)
        if "band" in data.dims:
            pair.dx = data.isel(band=0)
            pair.dy = data.isel(band=1)
        else:
            # Assume first two channels
            pair.dx = data[:, :, 0] if len(data.shape) == 3 else data
            pair.dy = data[:, :, 1] if len(data.shape) == 3 else data

    # Set zeros to NaN
    if pair.dx is not None:
        pair.dx = pair.dx.where(pair.dx != 0)
    if pair.dy is not None:
        pair.dy = pair.dy.where(pair.dy != 0)

    return pair


def filter_displacement_by_angle(
    dx: xr.DataArray,
    dy: xr.DataArray,
    threshold_degrees: float = 60.0,
    kernel_size: int = 3,
) -> xr.DataArray:
    """
    Filter displacement based on angular consistency with neighbors.

    Pixels are masked where the standard deviation of displacement angle
    over a neighborhood exceeds a threshold. This removes noise from
    areas with inconsistent displacement directions.

    Parameters
    ----------
    dx : xr.DataArray
        X-component of displacement.
    dy : xr.DataArray
        Y-component of displacement.
    threshold_degrees : float
        Maximum allowed angular std deviation in degrees.
    kernel_size : int
        Size of the neighborhood kernel.

    Returns
    -------
    xr.DataArray
        Boolean mask where True indicates valid pixels.

    Notes
    -----
    Replaces the MATLAB angle-based filtering in plotcosicorr.m.
    """
    # Calculate displacement angle in degrees
    angle = np.degrees(np.arctan2(dy.values, dx.values))

    # Create convolution kernel
    kernel = np.ones((kernel_size, kernel_size)) / (kernel_size ** 2)

    # Calculate local mean and std of angle
    # Handle NaN values by using nanmean via masked convolution
    angle_filled = np.nan_to_num(angle, nan=0.0)
    mask = ~np.isnan(angle)
    
    # Weighted convolution for mean
    weights = ndimage.convolve(mask.astype(float), kernel, mode="constant")
    weights = np.where(weights == 0, 1, weights)  # Avoid division by zero
    
    mean_angle = ndimage.convolve(angle_filled, kernel, mode="constant") / weights
    
    # Calculate std
    sq_diff = (angle_filled - mean_angle) ** 2
    var_angle = ndimage.convolve(sq_diff * mask, kernel, mode="constant") / weights
    std_angle = np.sqrt(np.abs(var_angle))

    # Create mask
    valid_mask = std_angle < threshold_degrees

    return xr.DataArray(
        valid_mask,
        dims=dx.dims,
        coords=dx.coords,
    )


def compute_displacement_magnitude(
    dx: xr.DataArray,
    dy: xr.DataArray,
) -> xr.DataArray:
    """
    Compute displacement magnitude from components.

    Parameters
    ----------
    dx : xr.DataArray
        X-component of displacement.
    dy : xr.DataArray
        Y-component of displacement.

    Returns
    -------
    xr.DataArray
        Displacement magnitude.
    """
    return np.sqrt(dx ** 2 + dy ** 2)


def resample_displacement(
    dx: xr.DataArray,
    dy: xr.DataArray,
    target_resolution: float,
    method: str = "mean",
) -> tuple[xr.DataArray, xr.DataArray]:
    """
    Resample displacement to target resolution.

    Parameters
    ----------
    dx : xr.DataArray
        X-component of displacement.
    dy : xr.DataArray
        Y-component of displacement.
    target_resolution : float
        Target resolution in meters.
    method : str
        Resampling method ("mean", "median").

    Returns
    -------
    tuple
        Resampled (dx, dy) arrays.
    """
    # Get current resolution
    current_dx = abs(float(dx.x[1] - dx.x[0]))
    current_dy = abs(float(dx.y[1] - dx.y[0]))

    if current_dx == 0 or current_dy == 0:
        return dx, dy

    # Calculate coarsening factors
    factor_x = max(1, int(round(target_resolution / current_dx)))
    factor_y = max(1, int(round(target_resolution / current_dy)))

    if factor_x == 1 and factor_y == 1:
        return dx, dy

    # Coarsen using specified method
    if method == "mean":
        dx_resampled = dx.coarsen(x=factor_x, y=factor_y, boundary="trim").mean()
        dy_resampled = dy.coarsen(x=factor_x, y=factor_y, boundary="trim").mean()
    elif method == "median":
        dx_resampled = dx.coarsen(x=factor_x, y=factor_y, boundary="trim").median()
        dy_resampled = dy.coarsen(x=factor_x, y=factor_y, boundary="trim").median()
    else:
        raise ValueError(f"Unknown resampling method: {method}")

    return dx_resampled, dy_resampled


class DisplacementStack:
    """
    Collection of displacement pairs for time-series analysis.

    Provides methods for loading, filtering, and stacking multiple
    displacement measurements with lazy evaluation via Dask.
    """

    def __init__(self, config: TSCorrConfig):
        """
        Initialize DisplacementStack.

        Parameters
        ----------
        config : TSCorrConfig
            Configuration object.
        """
        self.config = config
        self.pairs: list[DisplacementPair] = []
        self._stacked_dx: xr.DataArray | None = None
        self._stacked_dy: xr.DataArray | None = None
        self._times: NDArray | None = None

    def load_from_filelist(
        self,
        filelist_path: str | Path | None = None,
        chunks: dict[str, int] | None = None,
    ) -> None:
        """
        Load displacement pairs from a file list.

        Parameters
        ----------
        filelist_path : str or Path, optional
            Path to file containing list of correlation results.
            Defaults to config.paths.corr_file_list.
        chunks : dict, optional
            Chunk sizes for lazy loading.
        """
        if filelist_path is None:
            filelist_path = self.config.paths.corr_file_list

        filelist_path = Path(filelist_path)
        if not filelist_path.exists():
            raise FileNotFoundError(f"File list not found: {filelist_path}")

        with open(filelist_path) as f:
            filepaths = [line.strip() for line in f if line.strip()]

        self.load_from_paths(filepaths, chunks=chunks)

    def load_from_paths(
        self,
        filepaths: list[str | Path],
        chunks: dict[str, int] | None = None,
    ) -> None:
        """
        Load displacement pairs from a list of file paths.

        Parameters
        ----------
        filepaths : list
            List of file paths to load.
        chunks : dict, optional
            Chunk sizes for lazy loading.
        """
        if chunks is None and self.config.dask.chunk_size:
            chunks = self.config.dask.chunk_size

        for fp in filepaths:
            fp = Path(fp)
            if not fp.exists():
                print(f"Warning: File not found, skipping: {fp}")
                continue

            try:
                pair = load_displacement_pair(fp, self.config, chunks=chunks)

                # Apply temporal filter
                if not self.config.temporal.is_date_valid(pair.date_master):
                    continue
                if not self.config.temporal.is_date_valid(pair.date_secondary):
                    continue

                self.pairs.append(pair)
            except Exception as e:
                print(f"Warning: Could not load {fp}: {e}")

        print(f"Loaded {len(self.pairs)} displacement pairs")

    def filter_pairs(
        self,
        min_time_delta_days: float = 0,
        max_time_delta_days: float = float("inf"),
    ) -> None:
        """
        Filter pairs by time separation.

        Parameters
        ----------
        min_time_delta_days : float
            Minimum time difference in days.
        max_time_delta_days : float
            Maximum time difference in days.
        """
        self.pairs = [
            p for p in self.pairs
            if min_time_delta_days <= p.time_delta_days <= max_time_delta_days
        ]

    def stack(self) -> tuple[xr.DataArray, xr.DataArray, NDArray]:
        """
        Stack all displacement pairs into 3D arrays.

        Returns
        -------
        tuple
            (dx_stack, dy_stack, times)
            - dx_stack: 3D array (time, y, x) of x-displacements
            - dy_stack: 3D array (time, y, x) of y-displacements
            - times: 1D array of reference times (master dates)
        """
        if not self.pairs:
            raise ValueError("No pairs loaded")

        # Sort by master date
        self.pairs.sort(key=lambda p: p.date_master)

        # Get reference coordinates from first pair
        ref_pair = self.pairs[0]
        ref_x = ref_pair.dx.x.values
        ref_y = ref_pair.dx.y.values

        # Stack arrays
        dx_list = []
        dy_list = []
        times = []

        for pair in self.pairs:
            # Interpolate to reference grid if necessary
            dx = pair.dx.interp(x=ref_x, y=ref_y, method="linear")
            dy = pair.dy.interp(x=ref_x, y=ref_y, method="linear")

            dx_list.append(dx.values)
            dy_list.append(dy.values)
            times.append(pair.date_master)

        # Create stacked arrays
        self._stacked_dx = xr.DataArray(
            da.stack(dx_list),
            dims=["time", "y", "x"],
            coords={"time": times, "y": ref_y, "x": ref_x},
        )
        self._stacked_dy = xr.DataArray(
            da.stack(dy_list),
            dims=["time", "y", "x"],
            coords={"time": times, "y": ref_y, "x": ref_x},
        )
        self._times = np.array(times)

        return self._stacked_dx, self._stacked_dy, self._times

    @property
    def n_pairs(self) -> int:
        """Number of loaded pairs."""
        return len(self.pairs)

    @property
    def date_range(self) -> tuple[datetime, datetime] | None:
        """Date range of loaded pairs."""
        if not self.pairs:
            return None
        dates = [p.date_master for p in self.pairs] + [p.date_secondary for p in self.pairs]
        return min(dates), max(dates)
